[
  {
    nom: "Hauts-de-France",
    prefecture: "Lille",
    population: 6004497,
    superficie: 31806,
    départements: ["Aisne", "Nord", "Oise", "Pas-de-Calais", "Somme"],
  },
  {
    nom: "Île-de-France",
    prefecture: "Paris",
    population: 12262544,
    superficie: 12011,
    départements: [
      "Paris",
      "Seine-et-Marne",
      "Yvelines",
      "Essonne",
      "Hauts-de-Seine",
      "Seine-Saint-Denis",
      "Val-de-Marne",
      "Val-d'Oise",
    ],
  },
  {
    nom: "Normandie",
    prefecture: "Rouen",
    population: 3325032,
    superficie: 29906,
    départements: ["Calvados", "Eure", "Manche", "Orne", "Seine-Maritime"],
  },
  {
    nom: "Grand Est",
    chefLieu: "Strasbourg",
    population: 5556219,
    superficie: 57441,
    départements: [
      "Ardennes",
      "Aube",
      "Marne",
      "Haute-Marne",
      "Meurthe-et-Moselle",
      "Meuse",
      "Moselle",
      "Bas-Rhin",
      "Haut-Rhin",
      "Vosges",
    ],
  },
  {
    nom: "Bretagne",
    chefLieu: "Rennes",
    population: 3354854,
    superficie: 27209,
    départements: ["Côtes-d'Armor", "Finistère", "Ille-et-Vilaine", "Morbihan"],
  },
  {
    nom: "Pays de la Loire",
    chefLieu: "Nantes",
    population: 3806461,
    superficie: 32082,
    départements: ["Loire-Atlantique", "Maine-et-Loire", "Mayenne", "Sarthe", "Vendée"],
  },
  {
    nom: "Centre-Val de Loire",
    chefLieu: "Orléans",
    population: 2573180,
    superficie: 39151,
    départements: ["Cher", "Eure-et-Loir", "Indre", "Indre-et-Loir", "Loir-et-Cher", "Loiret"],
  },
  {
    nom: "Bourgogne-Franche-Comté",
    chefLieu: "Dijon",
    population: 2805580,
    superficie: 47784,
    départements: ["Côte d'Or", "Doubs", "Jura", "Nièvre", "Haute-Saône", "Saône-et-Loire", "Yonne", "Territoire de Belfort"],
  },
  {
    nom: "Nouvelle-Aquitaine",
    chefLieu: "Bordeaux",
    population: 6010289,
    superficie: 84036,
    départements: [
      "Charente",
      "Charente-Maritime",
      "Corrèze",
      "Creuse",
      "Dordogne",
      "Gironde",
      "Landes",
      "Lot-et-Garonne",
      "Pyrénées-Atlantiques",
      "Deux-Sèvres",
      "Vienne",
      "Haute-Vienne",
    ],
  },
  {
    nom: "Auvergne-Rhône-Alpes",
    chefLieu: "Lyon",
    population: 8042936,
    superficie: 69711,
    départements: [
      "Ain",
      "Allier",
      "Ardèche",
      "Cantal",
      "Drôme",
      "Isère",
      "Loire",
      "Haute-Loire",
      "Puy-de-Dôme",
      "Rhône",
      "Savoie",
      "Haute-Savoie",
    ],
  },
  {
    nom: "Occitanie",
    chefLieu: "Toulouse",
    population: 5933185,
    superficie: 72724,
    départements: [
      "Ariège",
      "Aude",
      "Aveyron",
      "Gard",
      "Haute-Garonne",
      "Gers",
      "Hérault",
      "Lot",
      "Lozère",
      "Hautes-Pyrénées",
      "Pyrénées-Orientales",
      "Tarn",
      "Tarn-et-Garonne",
    ],
  },
  {
    nom: "Provence-Alpes-Côte d'Azur",
    chefLieu: "Marseille",
    population: 5081101,
    superficie: 31400,
    départements: ["Alpes-de-Haute-Provence", "Hautes-Alpes", "Alpes-Maritimes", "Bouches-du-Rhône", "Var", "Vaucluse"],
  },
  {
    nom: "Corse",
    chefLieu: "Ajaccio",
    population: 340440,
    superficie: 8722,
    départements: ["Corse-du-Sud", "Haute-Corse"],
  },
];
